# Generated by Django 4.2.5 on 2023-10-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworkapp4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
